### PR TITLE
Added element type enum file

### PR DESCRIPTION
**Pull request by chiao45**
This PR adds the C++ enum definition for element types that are used in `sfelib`.

### CODE REVIEW

**Comment by xmjiao** [comment]
Thanks! Why is it put under `extern` instead of `src`?

**Comment by chiao45** [comment]
> Thanks! Why is it put under `extern` instead of `src`?

I tried to follow the `wlslib-cpp` structure.

**Comment by chiao45** [comment]
But this file is not "extern", so I should move to `src`

**Review by xmjiao — APPROVED** [review]

**Comment by chiao45** [comment]
> But this file is not "extern", so I should move to `src`

@xmjiao Moved to `src`

**Pull request merged**
